fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000, --enforce-all]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/emmeowzing/dynamic-continuation-orb
    rev: v3.7.1
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/emmeowzing/circleci-orb-pre-commit-hook
    rev: v1.3.2
    hooks:
    - id: circleci-orb-validate

  - repo: https://github.com/premiscale/pre-commit-hooks
    rev: v0.0.9
    hooks:
    -   id: msg-issue-prefix