description: |
  Run 'helm lint' against a particular chart. Can be ran against every chart in a repo by using a matrix.
executor: << parameters.executor >>
resource_class: << parameters.resource-class >>
parameters:
  resource-class:
    type: enum
    enum:
      - small
      - medium
      - large
      - xlarge
      - 2xlarge
      - premiscale/on-premise
    default: small
    description: Resource class to run as.
  executor:
    description: Executor image to run as.
    default: default
    type: executor
  chart-path:
    description: Path to Helm chart we wish to lint.
    type: string
    default: helm/
steps:
  - checkout
  - helm/install-helm-client
  - run:
      name: Helm lint
      command: helm lint << parameters.chart-path >>