description: |
  Run 'helm lint' against a particular chart. Can be ran against every chart in a repo by using a matrix.
executor: << parameters.executor >>
resource_class: << parameters.resource-class >>
parameters:
  resource-class:
    type: enum
    enum:
      - small
      - medium
      - large
      - xlarge
      - 2xlarge
      - premiscale/small
      - premiscale/medium
    default: small
    description: Resource class to run as.
  executor:
    description: Executor image to run as.
    default: default
    type: executor
  chart-path:
    description: Path to Helm chart we wish to lint.
    type: string
    default: ''
steps:
  - checkout
  - helm/install-helm-client
  # When there's a chart path specified.
  - when:
      condition: << parameters.chart-path >>
      steps:
        - run:
            name: Helm lint
            command: |+
              helm lint << parameters.chart-path >>
  #
  - unless:
      condition: << parameters.chart-path >>
      steps:
        - run:
            name: Helm lint
            command: |+
              mapfile -t _HELM_CHART_DIRECTORIES < <(find -type f -name "Chart.yaml" -exec dirname {} \;)

              for chart_path in "${_HELM_CHART_DIRECTORIES[@]}"; do
                  helm lint "$chart_path"
              done