description: |+
  Helm upgrade --install on a cluster.
parameters:
  namespace:
    default: default
    type: string
    description: Cluster namespace to deploy to.
  install-name:
    type: string
    description: The name to give the deployment.
    default: $CIRCLE_PROJECT_REPONAME
  uninstall-prev-name:
    type: string
    description: |+
      Name of another Helm installation managed for a different branch.

      This parameter is intended to be used with cross-namespace deployments with a gitflow like

          development branch -> master -> tags

      with 3 separate test namespaces for each.
    default: ''
  uninstall-prev-namespace:
    type: string
    description: |+
      Intended to be used in tandem with the 'uninstall-prev-name'-parameter. Specify a namespace, if different
      than the deployment, to perform the uninstall within.
    default: default
  additional-values:
    type: string
    default: ''
    description: Additional values.yaml-files to pass to helm.
  cluster:
    default: $CLUSTER
    type: string
    description: Cluster name to connect to.
  loft:
    description: Authenticate with Loft.
    type: boolean
    default: false
  loft-access-key:
    default: $LOFT_ACCESS_KEY
    type: string
    description: Loft.sh access key.
  loft-url:
    default: $LOFT_URL
    type: string
    description: Loft.sh deployment's domain.
  executor:
    description: Executor image to run as.
    default: default
    type: executor
  resource-class:
    type: enum
    enum:
      - small
      - medium
      - large
      - xlarge
      - 2xlarge
      - premiscale/small
      - premiscale/medium
    default: small
  repo:
    description: Nexus Helm repository URL.
    type: string
    default: $HELM_REPOSITORY_URL
  repo-name:
    type: string
    default: premiscale
    description: Repo alias (helm repo add <alias> <url>).
  username:
    description: Nexus Helm repository username.
    type: string
    default: $HELM_USERNAME
  password:
    description: Nexus Helm repository password.
    type: string
    default: $HELM_PASSWORD
  version:
    description: Version of the package to publish (helm package --version)
    type: string
    default: $CIRCLE_TAG
resource_class: << parameters.resource-class >>
executor: << parameters.executor >>
steps:
  - checkout
  - helm/install-helm-client
  - when:
      condition: << parameters.uninstall-prev-name >>
      steps:
        - run:
            name: Uninstall previous managed installation
            command: |+
              helm uninstall << parameters.uninstall-prev-name >> -n << parameters.uninstall-prev-namespace >>
  - helm-login:
      repo: << parameters.repo >>
      repo-name: << parameters.repo-name >>
      username: << parameters.username >>
      password: << parameters.password >>
  - when:
      condition: << parameters.loft >>
      steps:
        - loft-connect:
            cluster: << parameters.cluster >>
            loft-access-key: << parameters.loft-access-key >>
            loft-url: << parameters.loft-url >>
  - run:
      name: Helm upgrade --install
      command: |+
        helm upgrade --install --namespace "<< parameters.namespace >>" --create-namespace "<< parameters.install-name >>" << parameters.repo-name >>/<< parameters.install-name >> --version << parameters.version >> << parameters.additional-values >>